name: Deploy via FTP

on:
  push:
    branches:
      - main # Set this to your default branch

jobs:
  ftp-deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: List files in the repo
        run: ls -R

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}